import React,{useMemo,useState}from'react';

const NAV=['Dashboard','Admin Settings','Students','Staff','Fee Manager','Exam Manager','Attendance','Transport','Communication','Complaints','Reports'];
const initials={Dashboard:'D','Admin Settings':'S',Students:'G',Staff:'U','Fee Manager':'F','Exam Manager':'E',Attendance:'A',Transport:'T',Communication:'M',Complaints:'C',Reports:'R'};
const rows={
 Students:[['VJC-001','Aarav Sharma','Junior Inter','MPC','Active'],['VJC-002','Diya Reddy','Junior Inter','BiPC','Active'],['VJC-003','Kabir Rao','Senior Inter','MEC','Active'],['VJC-004','Ananya Iyer','Senior Inter','CEC','Active']],
 Staff:[['STF-014','Dr. R. Mehta','Sciences','Physics','Active'],['STF-021','Ms. S. Nair','Sciences','Chemistry','Active']],
 'Fee Manager':[['VJC-R-1048','Aarav Sharma','INR 48,000','INR 13,000','UPI'],['VJC-R-1047','Diya Reddy','INR 52,000','INR 0','Bank Transfer']],
 'Exam Manager':[['Unit Test I','Junior Inter','Mathematics','08 Jul 2026','Scheduled'],['Quarterly','Senior Inter','Economics','22 Aug 2026','Draft']],
 Attendance:[['Aarav Sharma','101','Junior Inter','20 / 22','91%'],['Diya Reddy','102','Junior Inter','21 / 22','95%'],['Kabir Rao','205','Senior Inter','18 / 22','82%']],
 Transport:[['TS 09 AB 4421','M. Ramesh','Kukatpally','8 stops','42 students'],['TS 10 CD 8310','K. Anand','Miyapur','11 stops','38 students']],
 Communication:[['Quarterly exam schedule','All Students','Principal','25 Jun 2026','Sent'],['Fee payment reminder','Junior Inter A','Accounts','23 Jun 2026','Sent']],
 Complaints:[['CMP-028','Student 102','Library access card','25 Jun 2026','Processing'],['CMP-027','Staff STF-021','Lab equipment request','24 Jun 2026','Pending']],
 Reports:[['Fee Collection Summary','Fees','June 2026','PDF / Excel'],['Student Attendance','Attendance','June 2026','PDF / Print'],['Class-wise Performance','Exams','Quarterly','PDF / Excel']]
};
const cols={Students:['Student ID','Name','Class','Course','Status'],Staff:['Staff ID','Name','Department','Subject','Status'],'Fee Manager':['Receipt','Student','Total','Balance','Mode'],'Exam Manager':['Exam','Class','Subject','Date','Status'],Attendance:['Student','Roll','Class','Present','Percentage'],Transport:['Bus','Driver','Route','Stops','Students'],Communication:['Subject','Audience','Sender','Date','Status'],Complaints:['ID','Raised By','Subject','Date','Status'],Reports:['Report','Module','Period','Formats']};
function App(){const[active,setActive]=useState('Dashboard'),[modal,setModal]=useState(''),[toast,setToast]=useState(''),[setting,setSetting]=useState('Academic Years');const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">V</div><div><b>VALUES</b><span>JUNIOR COLLEGE</span></div></div><nav>{NAV.map(n=><button key={n} onClick={()=>setActive(n)} className={active===n?'on':''}><strong>{initials[n]}</strong><span>{n}</span></button>)}</nav></aside><main><header><div><h1>{active}</h1><p>Values Junior College Management System</p></div><div className="headActions"><button onClick={()=>notify('3 new notifications available')}>Notifications</button><button onClick={()=>notify('Admin profile menu opened')}>AS&nbsp; Admin</button></div></header><section className="content">{active==='Dashboard'?<Dashboard setActive={setActive} notify={notify}/>:active==='Admin Settings'?<Settings setting={setting} setSetting={setSetting} notify={notify}/>:<Module name={active} setModal={setModal} notify={notify}/>}</section></main>{modal&&<Modal title={modal} close={()=>setModal('')} notify={notify}/>} {toast&&<div className="toast">{toast}</div>}</div>}
function Dashboard({setActive,notify}){const stats=[['4','Total Students'],['2','Total Staff'],['INR 42.8L','Fee Collection'],['INR 8.4L','Pending Fees'],['92.4%','Today Attendance'],['2','Messages'],['2','Complaints']];return <><div className="intro"><b>26 June 2026</b><h2>Good morning, Admin.</h2><p>Here is what is happening at Values Junior College today.</p></div><div className="stats">{stats.map(s=><div className="card stat" key={s[1]}><h3>{s[0]}</h3><p>{s[1]}</p></div>)}</div><div className="gridTwo"><div className="card chart"><h3>Fee Collection Overview</h3><div className="bars">{[36,50,44,58,68,62,75].map((h,i)=><span key={i} style={{height:h+'%'}} />)}</div></div><div className="card quick"><h3>Quick Actions</h3><div><button onClick={()=>setActive('Students')}>Add Student</button><button onClick={()=>setActive('Fee Manager')}>Fee Receipt</button><button onClick={()=>setActive('Exam Manager')}>Enter Marks</button><button onClick={()=>setActive('Communication')}>Send Notice</button></div></div></div><div className="card recent"><h3>Recent Activity</h3>{['Fee payment received - INR 24,500 from Aarav Sharma','New student admitted - Diya Reddy','Attendance submitted - Senior Inter A','Complaint resolved - Library access card'].map(x=><p key={x}>{x}</p>)}</div></>}
function Module({name,setModal,notify}){const data=rows[name]||[];return <><div className="moduleHead"><div><h2>{name}</h2><p>{name==='Reports'?'Consolidated academic, financial and operational reports.':'Manage '+name.toLowerCase()+' records and actions.'}</p></div>{name!=='Reports'&&<button className="primary" onClick={()=>setModal('Add '+name)}>Add New</button>}</div><div className="card tableCard"><div className="tools"><input placeholder={'Search '+name.toLowerCase()}/><select><option>All Classes</option><option>Junior Inter</option><option>Senior Inter</option></select><button onClick={()=>notify('Import ready for '+name)}>Import</button><button onClick={()=>notify('Export generated for '+name)}>Export</button></div><table><thead><tr>{(cols[name]||[]).map(c=><th key={c}>{c}</th>)}<th>Action</th></tr></thead><tbody>{data.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}<td><button onClick={()=>notify('Opened record details')}>View</button></td></tr>)}</tbody></table></div></>}
function Settings({setting,setSetting,notify}){return <><div className="moduleHead"><div><h2>Admin Settings</h2><p>Configure institution branding and academic structure.</p></div></div><div className="card settings"><h3>College Profile & Branding</h3><p>Changes apply throughout the ERP and generated documents.</p><div className="profile"><div className="bigLogo">V</div><button onClick={()=>notify('Logo upload ready')}>Upload College Logo</button></div><div className="form"><label>College Name<input defaultValue="Values Junior College"/></label><label>Phone<input defaultValue="+91 40 2345 6789"/></label><label>Email<input defaultValue="office@values.edu"/></label><label>Academic Year<input defaultValue="2026-27"/></label><label className="wide">Address<textarea defaultValue="Hyderabad, Telangana, India"/></label></div><div className="settingTabs">{['Academic Years','Classes','Sections','Courses','Subjects'].map(x=><button key={x} className={setting===x?'selected':''} onClick={()=>{setSetting(x);notify(x+' opened')}}>{x}</button>)}<button className="primary" onClick={()=>notify('Settings saved successfully')}>Save Settings</button></div><div className="settingPanel"><b>{setting}</b><p>{setting} configuration is open. Add, edit, or review records here.</p><button onClick={()=>notify('New '+setting+' item added')}>Add Item</button></div></div></>}
function Modal({title,close,notify}){return <div className="overlay"><div className="modal"><div><h3>{title}</h3><button onClick={close}>X</button></div><div className="form">{['Name / Title','Reference Number','Class / Department','Mobile Number','Email','Status'].map(f=><label key={f}>{f}<input/></label>)}</div><footer><button onClick={close}>Cancel</button><button className="primary" onClick={()=>{notify('Record saved successfully');close()}}>Save Record</button></footer></div></div>}
export default App;