import React, { useState } from 'react';
import { LayoutDashboard, Settings, GraduationCap, Users, WalletCards, ClipboardCheck, CalendarCheck, Bus, MessageSquareText, ShieldAlert, BarChart3, Bell, Menu, X, Plus, Search, Download, Upload, IndianRupee, ChevronDown, LockKeyhole, Mail, Eye, EyeOff, UserPlus, Receipt, BellRing, MoreHorizontal } from 'lucide-react';
import { AreaChart, Area, ResponsiveContainer, CartesianGrid, XAxis, YAxis, Tooltip } from 'recharts';
const navy = '#071b35';
const nav = [['Dashboard', LayoutDashboard], ['Admin Settings', Settings], ['Students', GraduationCap], ['Staff', Users], ['Fee Manager', WalletCards], ['Exam Manager', ClipboardCheck], ['Attendance', CalendarCheck], ['Transport', Bus], ['Communication', MessageSquareText], ['Complaints', ShieldAlert], ['Reports', BarChart3]];
const students = [{ id: 'VJC-2026-001', name: 'Aarav Sharma', admission: 'ADM26001', roll: '101', class: 'Junior Inter', section: 'A', course: 'MPC', mobile: '98765 43210', status: 'Active' }, { id: 'VJC-2026-002', name: 'Diya Reddy', admission: 'ADM26002', roll: '102', class: 'Junior Inter', section: 'A', course: 'BiPC', mobile: '98765 12340', status: 'Active' }, { id: 'VJC-2026-003', name: 'Kabir Rao', admission: 'ADM26003', roll: '205', class: 'Senior Inter', section: 'B', course: 'MEC', mobile: '98490 77881', status: 'Active' }, { id: 'VJC-2026-004', name: 'Ananya Iyer', admission: 'ADM26004', roll: '211', class: 'Senior Inter', section: 'A', course: 'CEC', mobile: '99887 22116', status: 'Active' }];
function Login({ go }) { const [show, setShow] = useState(false), [forgot, setForgot] = useState(false); return React.createElement("div", { className: "grid min-h-screen lg:grid-cols-2" },
    React.createElement("section", { className: "relative hidden overflow-hidden bg-navy p-14 text-white lg:flex lg:flex-col lg:justify-between" },
        React.createElement("div", { className: "absolute -right-20 -top-20 h-96 w-96 rounded-full bg-skybrand/20 blur-3xl" }),
        React.createElement(Brand, null),
        React.createElement("div", { className: "relative max-w-lg" },
            React.createElement("span", { className: "rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-semibold" }, "SMART CAMPUS ERP"),
            React.createElement("h1", { className: "mt-7 text-5xl font-black leading-tight" }, "Everything your campus needs, beautifully connected."),
            React.createElement("p", { className: "mt-5 text-lg leading-8 text-slate-300" }, "Manage academics, students, fees, attendance and communication from one secure workspace.")),
        React.createElement("p", { className: "relative text-xs text-slate-400" }, "\u00A9 2026 Values Junior College. All Rights Reserved.")),
    React.createElement("section", { className: "flex items-center justify-center p-6" },
        React.createElement("form", { onSubmit: e => { e.preventDefault(); forgot ? setForgot(false) : go(); }, className: "w-full max-w-md space-y-5" },
            React.createElement("div", null,
                React.createElement("h2", { className: "text-3xl font-black text-navy" }, forgot ? 'Reset your password' : 'Welcome back'),
                React.createElement("p", { className: "mt-2 text-slate-500" }, forgot ? 'We will send a secure reset link.' : 'Sign in to Values Junior College Management System.')),
            React.createElement("label", { className: "block" },
                React.createElement("span", { className: "mb-2 block text-sm font-semibold" }, "Email or username"),
                React.createElement("div", { className: "relative" },
                    React.createElement(Mail, { className: "absolute left-4 top-3.5 text-slate-400", size: 18 }),
                    React.createElement("input", { className: "field py-3 pl-11", defaultValue: forgot ? '' : 'admin@values.edu', required: true }))),
            !forgot && React.createElement(React.Fragment, null,
                React.createElement("label", { className: "block" },
                    React.createElement("span", { className: "mb-2 block text-sm font-semibold" }, "Password"),
                    React.createElement("div", { className: "relative" },
                        React.createElement(LockKeyhole, { className: "absolute left-4 top-3.5 text-slate-400", size: 18 }),
                        React.createElement("input", { type: show ? 'text' : 'password', className: "field py-3 pl-11", defaultValue: "Admin@123", required: true }),
                        React.createElement("button", { type: "button", onClick: () => setShow(!show), className: "absolute right-4 top-3.5 text-slate-400" }, show ? React.createElement(EyeOff, { size: 18 }) : React.createElement(Eye, { size: 18 })))),
                React.createElement("button", { type: "button", onClick: () => setForgot(true), className: "w-full text-right text-sm font-semibold text-sky-600" }, "Forgot password?")),
            React.createElement("button", { className: "btn w-full py-3.5" }, forgot ? 'Send Reset Link' : 'Sign In Securely'),
            forgot && React.createElement("button", { type: "button", onClick: () => setForgot(false), className: "w-full text-sm" }, "Back to sign in")))); }
function Brand({ small = false }) { return React.createElement("div", { className: "relative flex items-center gap-3" },
    React.createElement("div", { className: "grid h-11 w-11 place-items-center rounded-xl bg-skybrand text-xl font-black text-white" }, "V"),
    !small && React.createElement("div", null,
        React.createElement("div", { className: "font-black text-white" }, "VALUES"),
        React.createElement("div", { className: "text-[10px] tracking-[.15em] text-sky-200" }, "JUNIOR COLLEGE"))); }
function Shell({ active, setActive, children }) { const [open, setOpen] = useState(false), [mini, setMini] = useState(false); return React.createElement("div", null,
    React.createElement("aside", { className: `fixed inset-y-0 left-0 z-40 flex flex-col bg-navy transition-all ${open ? 'translate-x-0' : '-translate-x-full'} ${mini ? 'w-20' : 'w-64'} lg:translate-x-0` },
        React.createElement("div", { className: "flex h-20 items-center justify-between border-b border-white/10 px-5" },
            React.createElement(Brand, { small: mini }),
            React.createElement("button", { onClick: () => setOpen(false), className: "text-white lg:hidden" },
                React.createElement(X, null))),
        React.createElement("nav", { className: "flex-1 space-y-1 overflow-y-auto p-3" }, nav.map(([n, I]) => React.createElement("button", { key: n, title: n, onClick: () => { setActive(n); setOpen(false); }, className: `flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${active === n ? 'bg-skybrand text-white' : 'text-slate-300 hover:bg-white/10'} ${mini ? 'justify-center' : ''}` },
            React.createElement(I, { size: 19 }),
            !mini && n))),
        React.createElement("button", { onClick: () => setMini(!mini), className: "m-3 hidden rounded-xl border border-white/10 p-3 text-sm text-slate-300 lg:block" }, mini ? '→' : 'Collapse sidebar')),
    React.createElement("header", { className: `fixed right-0 top-0 z-20 flex h-20 items-center justify-between border-b bg-white/90 px-4 backdrop-blur transition-all md:px-8 ${mini ? 'lg:left-20' : 'lg:left-64'}` },
        React.createElement("div", { className: "flex items-center gap-3" },
            React.createElement("button", { onClick: () => setOpen(true), className: "lg:hidden" },
                React.createElement(Menu, null)),
            React.createElement("div", null,
                React.createElement("h1", { className: "text-xl font-bold text-navy" }, active),
                React.createElement("p", { className: "hidden text-xs text-slate-500 sm:block" }, "Values Junior College Management System"))),
        React.createElement("div", { className: "flex gap-3" },
            React.createElement("button", { className: "relative rounded-xl border p-2.5" },
                React.createElement(Bell, { size: 19 }),
                React.createElement("span", { className: "absolute right-2 top-2 h-2 w-2 rounded-full bg-rose-500" })),
            React.createElement("button", { className: "flex items-center gap-2 rounded-xl border p-1.5 pr-2" },
                React.createElement("span", { className: "grid h-8 w-8 place-items-center rounded-lg bg-navy text-xs font-bold text-white" }, "AS"),
                React.createElement("span", { className: "hidden text-left md:block" },
                    React.createElement("b", { className: "block text-xs" }, "Admin Staff"),
                    React.createElement("small", null, "Super Admin")),
                React.createElement(ChevronDown, { size: 14 })))),
    React.createElement("main", { className: `min-h-screen pt-20 transition-all ${mini ? 'lg:pl-20' : 'lg:pl-64'}` },
        React.createElement("div", { className: "p-4 md:p-8" }, children),
        React.createElement("footer", { className: "border-t bg-white p-5 text-center text-xs text-slate-500" }, "\u00A9 2026 Values Junior College. All Rights Reserved."))); }
const feeData = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'].map((m, i) => ({ m, c: [24, 29, 27, 34, 38, 36, 43][i], p: [12, 10, 11, 9, 8, 9, 8][i] }));
function Dashboard({ setActive }) { const stats = [['Total Students', '1,248', GraduationCap, 'blue'], ['Total Staff', '86', Users, 'violet'], ['Fee Collection', '₹42.8L', IndianRupee, 'emerald'], ['Pending Fees', '₹8.4L', WalletCards, 'amber'], ['Today Attendance', '92.4%', CalendarCheck, 'cyan'], ['Messages', '24', MessageSquareText, 'indigo'], ['Complaints', '7', ShieldAlert, 'rose']]; return React.createElement(React.Fragment, null,
    React.createElement("div", { className: "mb-7" },
        React.createElement("p", { className: "text-sm font-semibold text-sky-600" }, "26 June 2026"),
        React.createElement("h2", { className: "text-3xl font-black text-navy" }, "Good morning, Admin."),
        React.createElement("p", { className: "text-sm text-slate-500" }, "Here is what is happening at Values Junior College today.")),
    React.createElement("div", { className: "grid gap-4 sm:grid-cols-2 xl:grid-cols-4" }, stats.map(([l, v, I, c]) => React.createElement("div", { className: "card p-5", key: l },
        React.createElement("div", { className: `grid h-11 w-11 place-items-center rounded-xl bg-${c}-50 text-${c}-600` },
            React.createElement(I, { size: 21 })),
        React.createElement("div", { className: "mt-5 text-2xl font-black text-navy" }, v),
        React.createElement("div", { className: "text-sm text-slate-500" }, l)))),
    React.createElement("div", { className: "mt-6 grid gap-6 xl:grid-cols-3" },
        React.createElement("div", { className: "card p-5 xl:col-span-2" },
            React.createElement("h3", { className: "font-bold" }, "Fee Collection Overview"),
            React.createElement("div", { className: "h-72" },
                React.createElement(ResponsiveContainer, { width: "100%", height: "100%" },
                    React.createElement(AreaChart, { data: feeData },
                        React.createElement(CartesianGrid, { strokeDasharray: "3 3", vertical: false }),
                        React.createElement(XAxis, { dataKey: "m" }),
                        React.createElement(YAxis, null),
                        React.createElement(Tooltip, null),
                        React.createElement(Area, { type: "monotone", dataKey: "c", stroke: "#35a9e8", strokeWidth: 3, fill: "#dff3fd" }),
                        React.createElement(Area, { type: "monotone", dataKey: "p", stroke: "#f59e0b", fill: "transparent" }))))),
        React.createElement("div", { className: "card p-5" },
            React.createElement("h3", { className: "font-bold" }, "Quick Actions"),
            React.createElement("div", { className: "mt-4 grid grid-cols-2 gap-3" }, [['Add Student', UserPlus, 'Students'], ['Fee Receipt', Receipt, 'Fee Manager'], ['Enter Marks', ClipboardCheck, 'Exam Manager'], ['Send Notice', BellRing, 'Communication']].map(([l, I, p]) => React.createElement("button", { onClick: () => setActive(p), className: "rounded-xl border p-4 text-left hover:bg-sky-50", key: l },
                React.createElement(I, { className: "mb-3 text-sky-600" }),
                React.createElement("b", { className: "text-xs" }, l)))))),
    React.createElement("div", { className: "mt-6 card p-5" },
        React.createElement("h3", { className: "font-bold" }, "Recent Activity"),
        ['Fee payment received · ₹24,500 from Aarav Sharma', 'New student admitted · Diya Reddy', 'Attendance submitted · Senior Inter A', 'Complaint resolved · Library access card'].map(x => React.createElement("div", { className: "border-b py-4 text-sm", key: x }, x)))); }
const config = { Students: ['Manage admissions, profiles and academic details.', students, [['id', 'Student ID'], ['name', 'Student Name'], ['admission', 'Admission No.'], ['roll', 'Roll No.'], ['class', 'Class'], ['section', 'Section'], ['course', 'Course'], ['mobile', 'Mobile'], ['status', 'Status']]], Staff: ['Manage faculty, departments and login access.', [{ id: 'STF-014', name: 'Dr. R. Mehta', department: 'Sciences', subject: 'Physics', mobile: '98490 10001', joined: '12 Jun 2021' }, { id: 'STF-021', name: 'Ms. S. Nair', department: 'Sciences', subject: 'Chemistry', mobile: '98490 10002', joined: '04 Jul 2022' }], [['id', 'Staff ID'], ['name', 'Staff Name'], ['department', 'Department'], ['subject', 'Subject'], ['mobile', 'Mobile'], ['joined', 'Joining Date']]], 'Fee Manager': ['Track fee structures, allocations, payments and receipts.', [{ id: 1, receipt: 'VJC-R-1048', student: 'Aarav Sharma', total: '₹48,000', paid: '₹35,000', balance: '₹13,000', mode: 'UPI' }, { id: 2, receipt: 'VJC-R-1047', student: 'Diya Reddy', total: '₹52,000', paid: '₹52,000', balance: '₹0', mode: 'Bank Transfer' }], [['receipt', 'Receipt'], ['student', 'Student'], ['total', 'Total'], ['paid', 'Paid'], ['balance', 'Balance'], ['mode', 'Mode']]], 'Exam Manager': ['Create exams, enter marks and publish report cards.', [{ id: 1, exam: 'Unit Test I', class: 'Junior Inter', subject: 'Mathematics', date: '08 Jul 2026', max: 50, status: 'Scheduled' }, { id: 2, exam: 'Quarterly', class: 'Senior Inter', subject: 'Economics', date: '22 Aug 2026', max: 100, status: 'Draft' }], [['exam', 'Exam'], ['class', 'Class'], ['subject', 'Subject'], ['date', 'Date'], ['max', 'Max Marks'], ['status', 'Status']]], Attendance: ['Record daily attendance and analyze presence.', students.map((s, i) => ({ id: i, student: s.name, roll: s.roll, class: s.class, days: 22, present: 20 - i, absent: 2 + i, percentage: (91 - i * 5) + '%' })), [['student', 'Student'], ['roll', 'Roll'], ['class', 'Class'], ['days', 'Days'], ['present', 'Present'], ['absent', 'Absent'], ['percentage', 'Percentage']]], Transport: ['Manage buses, routes, stops and student allocation.', [{ id: 1, bus: 'TS 09 AB 4421', driver: 'M. Ramesh', mobile: '98491 12231', route: 'Kukatpally', stops: 8, students: 42 }, { id: 2, bus: 'TS 10 CD 8310', driver: 'K. Anand', mobile: '98491 14452', route: 'Miyapur', stops: 11, students: 38 }], [['bus', 'Bus Number'], ['driver', 'Driver'], ['mobile', 'Mobile'], ['route', 'Route'], ['stops', 'Stops'], ['students', 'Students']]], Communication: ['Publish notices and targeted campus messages.', [{ id: 1, subject: 'Quarterly exam schedule', audience: 'All Students', sender: 'Principal', date: '25 Jun 2026', status: 'Sent' }, { id: 2, subject: 'Fee payment reminder', audience: 'Junior Inter A', sender: 'Accounts', date: '23 Jun 2026', status: 'Sent' }], [['subject', 'Subject'], ['audience', 'Audience'], ['sender', 'Sender'], ['date', 'Date'], ['status', 'Status']]], Complaints: ['Track, assign and resolve concerns.', [{ id: 1, code: 'CMP-028', from: 'Student · 102', subject: 'Library access card', date: '25 Jun 2026', status: 'Processing' }, { id: 2, code: 'CMP-027', from: 'Staff · STF-021', subject: 'Lab equipment request', date: '24 Jun 2026', status: 'Pending' }], [['code', 'Complaint ID'], ['from', 'Raised By'], ['subject', 'Subject'], ['date', 'Date'], ['status', 'Status']]], Reports: ['Consolidated academic, financial and operational reports.', [{ id: 1, name: 'Fee Collection Summary', module: 'Fees', period: 'June 2026', format: 'PDF · Excel' }, { id: 2, name: 'Student Attendance', module: 'Attendance', period: 'June 2026', format: 'PDF · Print' }, { id: 3, name: 'Class-wise Performance', module: 'Exams', period: 'Quarterly', format: 'PDF · Excel' }], [['name', 'Report'], ['module', 'Module'], ['period', 'Period'], ['format', 'Formats']]] };
function Table({ cols, rows }) { return React.createElement("div", { className: "overflow-x-auto" },
    React.createElement("table", { className: "w-full text-left text-sm" },
        React.createElement("thead", { className: "bg-slate-50 text-xs uppercase text-slate-500" },
            React.createElement("tr", null,
                cols.map(([k, l]) => React.createElement("th", { className: "px-5 py-4", key: k }, l)),
                React.createElement("th", null))),
        React.createElement("tbody", { className: "divide-y" }, rows.map((r, i) => React.createElement("tr", { className: "hover:bg-sky-50/40", key: r.id || i },
            cols.map(([k]) => React.createElement("td", { className: "whitespace-nowrap px-5 py-4", key: k }, k === 'status' ? React.createElement("span", { className: "rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700" }, r[k]) : r[k])),
            React.createElement("td", null,
                React.createElement(MoreHorizontal, null)))))),
    React.createElement("div", { className: "flex justify-between border-t p-4 text-xs text-slate-500" },
        React.createElement("span", null,
            "Showing ",
            rows.length,
            " records"),
        React.createElement("span", null, "Previous \u00B7 1 \u00B7 Next"))); }
function Module({ type }) { const [desc, rows, cols] = config[type], [modal, setModal] = useState(false); return React.createElement(React.Fragment, null,
    React.createElement(Header, { title: type, desc: desc, add: type === 'Reports' ? null : () => setModal(true) }),
    React.createElement("div", { className: "card overflow-hidden" },
        React.createElement("div", { className: "flex flex-col gap-3 border-b p-4 md:flex-row md:justify-between" },
            React.createElement("div", { className: "relative" },
                React.createElement(Search, { className: "absolute left-3 top-3 text-slate-400", size: 17 }),
                React.createElement("input", { className: "field pl-9", placeholder: 'Search ' + type.toLowerCase() })),
            React.createElement("div", { className: "flex gap-2" },
                React.createElement("select", { className: "field" },
                    React.createElement("option", null, "All Classes"),
                    React.createElement("option", null, "Junior Inter"),
                    React.createElement("option", null, "Senior Inter")),
                React.createElement("button", { className: "btn2" },
                    React.createElement(Upload, { size: 16 }),
                    "Import"),
                React.createElement("button", { className: "btn2" },
                    React.createElement(Download, { size: 16 }),
                    "Export"))),
        React.createElement(Table, { cols: cols, rows: rows })),
    modal && React.createElement(Modal, { title: 'Add ' + type, close: () => setModal(false) })); }
function Header({ title, desc, add }) { return React.createElement("div", { className: "mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center" },
    React.createElement("div", null,
        React.createElement("h2", { className: "text-2xl font-black text-navy" }, title),
        React.createElement("p", { className: "text-sm text-slate-500" }, desc)),
    add && React.createElement("button", { onClick: add, className: "btn" },
        React.createElement(Plus, { size: 17 }),
        "Add New")); }
function Modal({ title, close }) { return React.createElement("div", { className: "fixed inset-0 z-50 grid place-items-center bg-navy/60 p-4" },
    React.createElement("div", { className: "max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white" },
        React.createElement("div", { className: "flex justify-between border-b p-5" },
            React.createElement("b", null, title),
            React.createElement("button", { onClick: close },
                React.createElement(X, null))),
        React.createElement("div", { className: "grid gap-4 p-5 sm:grid-cols-2" }, ['Name / Title', 'Admission / Reference Number', 'Class / Department', 'Section / Subject', 'Mobile Number', 'Email', 'Date', 'Status', 'Address / Description'].map(f => React.createElement("label", { key: f },
            React.createElement("span", { className: "mb-1 block text-xs font-semibold" }, f),
            React.createElement("input", { className: "field" })))),
        React.createElement("div", { className: "flex justify-end gap-2 border-t p-5" },
            React.createElement("button", { onClick: close, className: "btn2" }, "Cancel"),
            React.createElement("button", { onClick: close, className: "btn" }, "Save Record")))); }
function SettingsPage() { return React.createElement(React.Fragment, null,
    React.createElement(Header, { title: "Admin Settings", desc: "Configure institution branding and academic structure." }),
    React.createElement("div", { className: "card p-6" },
        React.createElement("h3", { className: "text-lg font-bold" }, "College Profile & Branding"),
        React.createElement("p", { className: "text-xs text-slate-500" }, "Changes apply throughout the ERP and generated documents."),
        React.createElement("div", { className: "my-6 flex gap-4" },
            React.createElement("div", { className: "grid h-20 w-20 place-items-center rounded-2xl bg-navy text-3xl font-black text-white" }, "V"),
            React.createElement("button", { className: "btn2 self-center" },
                React.createElement(Upload, { size: 16 }),
                "Upload College Logo")),
        React.createElement("div", { className: "grid gap-4 sm:grid-cols-2" },
            React.createElement("label", null,
                React.createElement("small", null, "College Name"),
                React.createElement("input", { className: "field", defaultValue: "Values Junior College" })),
            React.createElement("label", null,
                React.createElement("small", null, "Phone"),
                React.createElement("input", { className: "field", defaultValue: "+91 40 2345 6789" })),
            React.createElement("label", null,
                React.createElement("small", null, "Email"),
                React.createElement("input", { className: "field", defaultValue: "office@values.edu" })),
            React.createElement("label", null,
                React.createElement("small", null, "Academic Year"),
                React.createElement("input", { className: "field", defaultValue: "2026\u201327" })),
            React.createElement("label", { className: "sm:col-span-2" },
                React.createElement("small", null, "Address"),
                React.createElement("textarea", { className: "field", defaultValue: "Hyderabad, Telangana, India" }))),
        React.createElement("div", { className: "mt-6 flex flex-wrap gap-2" },
            ['Academic Years', 'Classes', 'Sections', 'Courses', 'Subjects'].map(x => React.createElement("button", { className: "btn2", key: x }, x)),
            React.createElement("button", { className: "btn" }, "Save Settings")))); }
function App() { const [logged, setLogged] = useState(localStorage.values_session === '1'), [active, setActive] = useState('Dashboard'); if (!logged)
    return React.createElement(Login, { go: () => { localStorage.values_session = '1'; setLogged(true); } }); return React.createElement(Shell, { active: active, setActive: setActive }, active === 'Dashboard' ? React.createElement(Dashboard, { setActive: setActive }) : active === 'Admin Settings' ? React.createElement(SettingsPage, null) : React.createElement(Module, { type: active })); }


const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(React.createElement(App));
