import ReactDOM from 'react-dom/client';
import React, { useState } from 'react';
const NAV = ['Dashboard', 'Admin Settings', 'Students', 'Staff', 'Fee Manager', 'Exam Manager', 'Attendance', 'Transport', 'Communication', 'Complaints', 'Reports'];
const initials = { Dashboard: '▦', 'Admin Settings': '⚙', Students: '🎓', Staff: '👥', 'Fee Manager': '₹', 'Exam Manager': '✓', Attendance: '📅', Transport: '🚌', Communication: '✉', Complaints: '⚠', Reports: '▤' };
const students = [{ id: 'VJC-2026-001', name: 'Aarav Sharma', admission: 'ADM26001', roll: '101', class: 'Junior Inter', section: 'A', course: 'MPC', mobile: '98765 43210', email: 'aarav@values.edu', dob: '2009-04-18', guardian: 'Rajesh Sharma', parentMobile: '98765 43211', address: 'Hyderabad, Telangana', status: 'Active' }, { id: 'VJC-2026-002', name: 'Diya Reddy', admission: 'ADM26002', roll: '102', class: 'Junior Inter', section: 'A', course: 'BiPC', mobile: '98765 12340', email: 'diya@values.edu', dob: '2009-08-22', guardian: 'Suresh Reddy', parentMobile: '98765 12341', address: 'Hyderabad, Telangana', status: 'Active' }, { id: 'VJC-2026-003', name: 'Kabir Rao', admission: 'ADM26003', roll: '205', class: 'Senior Inter', section: 'B', course: 'MEC', mobile: '98490 77881', email: 'kabir@values.edu', dob: '2008-11-04', guardian: 'Meera Rao', parentMobile: '98490 77882', address: 'Secunderabad, Telangana', status: 'Active' }, { id: 'VJC-2026-004', name: 'Ananya Iyer', admission: 'ADM26004', roll: '211', class: 'Senior Inter', section: 'A', course: 'CEC', mobile: '99887 22116', email: 'ananya@values.edu', dob: '2008-06-15', guardian: 'Vikram Iyer', parentMobile: '99887 22117', address: 'Hyderabad, Telangana', status: 'Active' }];
const rows = { Students: students.map(s => [s.id, s.name, s.class, s.course, s.mobile, s.status]), Staff: [['STF-014', 'Dr. R. Mehta', 'Sciences', 'Physics', 'Active'], ['STF-021', 'Ms. S. Nair', 'Sciences', 'Chemistry', 'Active']], 'Fee Manager': [['VJC-R-1048', 'Aarav Sharma', 'INR 48,000', 'INR 13,000', 'UPI'], ['VJC-R-1047', 'Diya Reddy', 'INR 52,000', 'INR 0', 'Bank Transfer']], 'Exam Manager': [['Unit Test I', 'Junior Inter', 'Mathematics', '08 Jul 2026', 'Scheduled'], ['Quarterly', 'Senior Inter', 'Economics', '22 Aug 2026', 'Draft']], Attendance: [['Aarav Sharma', '101', 'Junior Inter', '20 / 22', '91%'], ['Diya Reddy', '102', 'Junior Inter', '21 / 22', '95%'], ['Kabir Rao', '205', 'Senior Inter', '18 / 22', '82%']], Transport: [['TS 09 AB 4421', 'M. Ramesh', 'Kukatpally', '8 stops', '42 students'], ['TS 10 CD 8310', 'K. Anand', 'Miyapur', '11 stops', '38 students']], Communication: [['Quarterly exam schedule', 'All Students', 'Principal', '25 Jun 2026', 'Sent'], ['Fee payment reminder', 'Junior Inter A', 'Accounts', '23 Jun 2026', 'Sent']], Complaints: [['CMP-028', 'Student 102', 'Library access card', '25 Jun 2026', 'Processing'], ['CMP-027', 'Staff STF-021', 'Lab equipment request', '24 Jun 2026', 'Pending']], Reports: [['Fee Collection Summary', 'Fees', 'June 2026', 'PDF / Excel'], ['Student Attendance', 'Attendance', 'June 2026', 'PDF / Print'], ['Class-wise Performance', 'Exams', 'Quarterly', 'PDF / Excel']] };
const cols = { Students: ['Student ID', 'Name', 'Class', 'Course', 'Mobile', 'Status'], Staff: ['Staff ID', 'Name', 'Department', 'Subject', 'Status'], 'Fee Manager': ['Receipt', 'Student', 'Total', 'Balance', 'Mode'], 'Exam Manager': ['Exam', 'Class', 'Subject', 'Date', 'Status'], Attendance: ['Student', 'Roll', 'Class', 'Present', 'Percentage'], Transport: ['Bus', 'Driver', 'Route', 'Stops', 'Students'], Communication: ['Subject', 'Audience', 'Sender', 'Date', 'Status'], Complaints: ['ID', 'Raised By', 'Subject', 'Date', 'Status'], Reports: ['Report', 'Module', 'Period', 'Formats'] };
const subtitles = { Staff: 'Complete staff profile', 'Fee Manager': 'Complete fee transaction details', 'Exam Manager': 'Complete exam details', Attendance: 'Complete attendance details', Transport: 'Complete transport route details', Communication: 'Complete message details', Complaints: 'Complete complaint details', Reports: 'Complete report details' };
function App() { const [active, setActive] = useState('Dashboard'), [modal, setModal] = useState(null), [toast, setToast] = useState(''), [setting, setSetting] = useState('Academic Years'); const notify = m => { setToast(m); setTimeout(() => setToast(''), 2200); }; const openDetail = (section, i) => section === 'Students' ? setModal({ type: 'student', student: students[i] || students[0] }) : setModal({ type: 'detail', section, row: rows[section][i], columns: cols[section] }); return React.createElement("div", { className: "app" },
    React.createElement("aside", { className: "sidebar" },
        React.createElement("div", { className: "brand" },
            React.createElement("div", { className: "logo" }, "V"),
            React.createElement("div", null,
                React.createElement("b", null, "VALUES"),
                React.createElement("span", null, "JUNIOR COLLEGE"))),
        React.createElement("nav", null, NAV.map(n => React.createElement("button", { key: n, onClick: () => setActive(n), className: active === n ? 'on' : '' },
            React.createElement("strong", null, initials[n]),
            React.createElement("span", null, n))))),
    React.createElement("main", null,
        React.createElement("header", null,
            React.createElement("div", null,
                React.createElement("h1", null, active),
                React.createElement("p", null, "Values Junior College Management System")),
            React.createElement("div", { className: "headActions" },
                React.createElement("button", { onClick: () => setModal({ type: 'notifications' }) }, "Notifications"),
                React.createElement("button", { onClick: () => setModal({ type: 'admin' }) }, "AS\u00A0 Admin"))),
        React.createElement("section", { className: "content" }, active === 'Dashboard' ? React.createElement(Dashboard, { setActive: setActive }) : active === 'Admin Settings' ? React.createElement(Settings, { setting: setting, setSetting: setSetting, notify: notify }) : React.createElement(Module, { name: active, setModal: setModal, notify: notify, openDetail: openDetail }))),
    modal?.type === 'add' && React.createElement(AddModal, { title: modal.title, close: () => setModal(null), notify: notify }),
    " ",
    modal?.type === 'student' && React.createElement(StudentModal, { student: modal.student, close: () => setModal(null), notify: notify }),
    " ",
    modal?.type === 'detail' && React.createElement(DetailModal, { section: modal.section, row: modal.row, columns: modal.columns, close: () => setModal(null), notify: notify }),
    " ",
    modal?.type === 'notifications' && React.createElement(InfoModal, { title: "Notifications", close: () => setModal(null), footer: React.createElement("button", { onClick: () => setModal(null) }, "Close") },
        React.createElement("p", null, "No urgent alerts right now."),
        React.createElement("p", null, "Fee reminders and exam notices are ready in Communication.")),
    " ",
    modal?.type === 'admin' && React.createElement(InfoModal, { title: "AS Admin", close: () => setModal(null), footer: React.createElement("button", { onClick: () => setModal(null) }, "Close") },
        React.createElement("p", null, "Signed in as Super Admin."),
        React.createElement("p", null, "Profile and account controls are ready.")),
    " ",
    toast && React.createElement("div", { className: "toast" }, toast)); }
function Dashboard({ setActive }) { const stats = [['4', 'Total Students'], ['2', 'Total Staff'], ['INR 42.8L', 'Fee Collection'], ['INR 8.4L', 'Pending Fees'], ['92.4%', 'Today Attendance'], ['2', 'Messages'], ['2', 'Complaints']]; return React.createElement(React.Fragment, null,
    React.createElement("div", { className: "intro" },
        React.createElement("b", null, "26 June 2026"),
        React.createElement("h2", null, "Good morning, Admin."),
        React.createElement("p", null, "Here is what is happening at Values Junior College today.")),
    React.createElement("div", { className: "stats" }, stats.map(s => React.createElement("div", { className: "card stat", key: s[1] },
        React.createElement("h3", null, s[0]),
        React.createElement("p", null, s[1])))),
    React.createElement("div", { className: "gridTwo" },
        React.createElement("div", { className: "card chart" },
            React.createElement("h3", null, "Fee Collection Overview"),
            React.createElement("div", { className: "bars" }, [36, 50, 44, 58, 68, 62, 75].map((h, i) => React.createElement("span", { key: i, style: { height: h + '%' } })))),
        React.createElement("div", { className: "card quick" },
            React.createElement("h3", null, "Quick Actions"),
            React.createElement("div", null,
                React.createElement("button", { onClick: () => setActive('Students') }, "Add Student"),
                React.createElement("button", { onClick: () => setActive('Fee Manager') }, "Fee Receipt"),
                React.createElement("button", { onClick: () => setActive('Exam Manager') }, "Enter Marks"),
                React.createElement("button", { onClick: () => setActive('Communication') }, "Send Notice")))),
    React.createElement("div", { className: "card recent" },
        React.createElement("h3", null, "Recent Activity"),
        ['Fee payment received - INR 24,500 from Aarav Sharma', 'New student admitted - Diya Reddy', 'Attendance submitted - Senior Inter A', 'Complaint resolved - Library access card'].map(x => React.createElement("p", { key: x }, x)))); }
function Module({ name, setModal, notify, openDetail }) { const data = rows[name] || []; return React.createElement(React.Fragment, null,
    React.createElement("div", { className: "moduleHead" },
        React.createElement("div", null,
            React.createElement("h2", null, name),
            React.createElement("p", null, name === 'Reports' ? 'Consolidated academic, financial and operational reports.' : 'Add, view, search and manage ' + name.toLowerCase() + '.')),
        name !== 'Reports' && React.createElement("button", { className: "primary", onClick: () => setModal({ type: 'add', title: 'Add ' + name }) }, "Add New")),
    React.createElement("div", { className: "card tableCard" },
        React.createElement("div", { className: "tools" },
            React.createElement("input", { placeholder: name === 'Students' ? 'Search by name, ID or mobile' : 'Search ' + name.toLowerCase() }),
            React.createElement("select", null,
                React.createElement("option", null, "All Classes"),
                React.createElement("option", null, "Junior Inter"),
                React.createElement("option", null, "Senior Inter")),
            React.createElement("button", { onClick: () => notify('Import ready for ' + name) }, "Import"),
            React.createElement("button", { onClick: () => notify('Export generated for ' + name) }, "Export")),
        React.createElement("table", null,
            React.createElement("thead", null,
                React.createElement("tr", null,
                    (cols[name] || []).map(c => React.createElement("th", { key: c }, c)),
                    React.createElement("th", null, "Action"))),
            React.createElement("tbody", null, data.map((r, i) => React.createElement("tr", { key: i },
                r.map((c, j) => React.createElement("td", { key: j }, c)),
                React.createElement("td", null,
                    React.createElement("button", { className: "dots", title: name + ' details', "aria-label": name + ' details', onClick: () => openDetail(name, i) }, "...")))))),
        React.createElement("div", { className: "showing" },
            "Showing ",
            data.length,
            " of ",
            data.length))); }
function Settings({ setting, setSetting, notify }) { return React.createElement(React.Fragment, null,
    React.createElement("div", { className: "moduleHead" },
        React.createElement("div", null,
            React.createElement("h2", null, "Admin Settings"),
            React.createElement("p", null, "Configure institution branding and academic structure."))),
    React.createElement("div", { className: "card settings" },
        React.createElement("h3", null, "College Profile & Branding"),
        React.createElement("p", null, "Changes apply throughout the ERP and generated documents."),
        React.createElement("div", { className: "profile" },
            React.createElement("div", { className: "bigLogo" }, "V"),
            React.createElement("button", { onClick: () => notify('Logo upload ready') }, "Upload College Logo")),
        React.createElement("div", { className: "form" },
            React.createElement("label", null,
                "College Name",
                React.createElement("input", { defaultValue: "Values Junior College" })),
            React.createElement("label", null,
                "Phone",
                React.createElement("input", { defaultValue: "+91 40 2345 6789" })),
            React.createElement("label", null,
                "Email",
                React.createElement("input", { defaultValue: "office@values.edu" })),
            React.createElement("label", null,
                "Academic Year",
                React.createElement("input", { defaultValue: "2026-27" })),
            React.createElement("label", { className: "wide" },
                "Address",
                React.createElement("textarea", { defaultValue: "Hyderabad, Telangana, India" }))),
        React.createElement("div", { className: "settingTabs" },
            ['Academic Years', 'Classes', 'Sections', 'Courses', 'Subjects'].map(x => React.createElement("button", { key: x, className: setting === x ? 'selected' : '', onClick: () => { setSetting(x); notify(x + ' opened'); } }, x)),
            React.createElement("button", { className: "primary", onClick: () => notify('Settings saved successfully') }, "Save Settings")),
        React.createElement("div", { className: "settingPanel" },
            React.createElement("b", null, setting),
            React.createElement("p", null,
                setting,
                " configuration is open. Add, edit, or review records here."),
            React.createElement("button", { onClick: () => notify('New ' + setting + ' item added') }, "Add Item")))); }
function InfoModal({ title, children, close, footer }) { return React.createElement("div", { className: "overlay" },
    React.createElement("div", { className: "dialog info" },
        React.createElement("div", { className: "dialogHead" },
            React.createElement("div", null,
                React.createElement("h3", null, title)),
            React.createElement("button", { className: "x", onClick: close }, "x")),
        React.createElement("div", { className: "dialogBody" }, children),
        React.createElement("footer", null, footer))); }
function DetailModal({ section, row, columns, close, notify }) { const title = row?.[1] || row?.[0] || section; return React.createElement("div", { className: "overlay" },
    React.createElement("div", { className: "dialog studentDialog" },
        React.createElement("div", { className: "dialogHead" },
            React.createElement("div", null,
                React.createElement("h3", null, title),
                React.createElement("p", null, subtitles[section] || ('Complete ' + section.toLowerCase() + ' details'))),
            React.createElement("button", { className: "x", onClick: close }, "x")),
        React.createElement("div", { className: "detailGrid" }, columns.map((c, i) => React.createElement("div", { className: "detail", key: c },
            React.createElement("b", null, c.toUpperCase()),
            React.createElement("span", null, row[i])))),
        React.createElement("footer", null,
            React.createElement("button", { className: "danger", onClick: () => notify(section + ' delete action opened') },
                "Delete ",
                section.replace(' Manager', '')),
            React.createElement("button", { onClick: close }, "Close")))); }
function StudentModal({ student, close, notify }) { const fields = [['STUDENT ID', student.id], ['ADMISSION NUMBER', student.admission], ['ROLL NUMBER', student.roll], ['CLASS', student.class], ['SECTION', student.section], ['COURSE', student.course], ['MOBILE', student.mobile], ['EMAIL', student.email], ['DATE OF BIRTH', student.dob], ['PARENT / GUARDIAN', student.guardian], ['PARENT MOBILE', student.parentMobile], ['ADDRESS', student.address], ['STATUS', student.status]]; return React.createElement("div", { className: "overlay" },
    React.createElement("div", { className: "dialog studentDialog" },
        React.createElement("div", { className: "dialogHead" },
            React.createElement("div", null,
                React.createElement("h3", null, student.name),
                React.createElement("p", null, "Complete student profile")),
            React.createElement("button", { className: "x", onClick: close }, "x")),
        React.createElement("div", { className: "detailGrid" }, fields.map(([k, v]) => React.createElement("div", { className: "detail", key: k },
            React.createElement("b", null, k),
            React.createElement("span", null, v)))),
        React.createElement("footer", null,
            React.createElement("button", { className: "danger", onClick: () => notify('Delete student action opened') }, "Delete Student"),
            React.createElement("button", { onClick: close }, "Close")))); }
function AddModal({ title, close, notify }) { return React.createElement("div", { className: "overlay" },
    React.createElement("div", { className: "dialog" },
        React.createElement("div", { className: "dialogHead" },
            React.createElement("div", null,
                React.createElement("h3", null, title)),
            React.createElement("button", { className: "x", onClick: close }, "x")),
        React.createElement("div", { className: "form modalForm" }, ['Name / Title', 'Reference Number', 'Class / Department', 'Mobile Number', 'Email', 'Status'].map(f => React.createElement("label", { key: f },
            f,
            React.createElement("input", null)))),
        React.createElement("footer", null,
            React.createElement("button", { onClick: close }, "Cancel"),
            React.createElement("button", { className: "primary", onClick: () => { notify('Record saved successfully'); close(); } }, "Save Record")))); }

const root=ReactDOM.createRoot(document.getElementById('root'));root.render(React.createElement(App));
